name: store_house
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  jiffy: ^6.3.1
  intl: ^0.19.0
  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  sqflite: ^2.4.2
  shared_preferences: ^2.3.2
  path: ^1.9.0
  qr_flutter: ^4.1.0
  grouped_list: ^6.0.0
  dropdown_search: ^6.0.0
  badges: ^3.1.2
  font_awesome_flutter: ^10.7.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^7.2.0
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1
  lottie: ^3.1.2
  flutter_ringtone_player: ^4.0.0+4
  permission_handler: ^12.0.1
  firebase_auth: ^6.1.2
  pin_code_fields: ^8.0.1
  file_picker: ^10.2.0
  auto_size_text: ^3.0.0
  flutter_image_compress: ^2.4.0
  http_parser: ^4.1.2
  path_provider: ^2.1.5
  rename: ^3.1.0
  flutter_lints: ^5.0.0
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro/ReadexPro-Bold.ttf
          weight: 700
